services:
  db:
    image: postgres:16
    container_name: cuentas_uber_db
    environment:
      POSTGRES_USER: cuentas_uber
      POSTGRES_PASSWORD: cuentas_uber
      POSTGRES_DB: cuentas_uber
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: